add login view
wecode-bootcamp-korea/GoinOne-backend pull request #3
Opened 2020-03-12 14:13 UTC by Wave1994-Hoon

## 수정 사항 간략한 한줄 요약
- 회원가입 / 로그인 기능 추가

## 수정 사항들 자세한 내용
- 회원가입 뷰 추가
- 로그인 뷰 추가
- 인증 데코레이터, 문자열 필터 데코레이터 추가
- 테스트 코드 추가

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)

- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [X] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-03-12 14:49 UTC, evergreen-david commented on account/utils.py
> +
빈칸은 삭제해주세요

2020-03-12 14:49 UTC, evergreen-david commented on account/utils.py
> +
함수 사이는 한칸만 띄워주세요

2020-03-12 14:49 UTC, evergreen-david commented on account/tests.py
> +        self.assertEqual(response.json(), {"message" : "INVALUD_KEY"})
```suggestion
        self.assertEqual(response.json(), {"message" : "INVALID_KEY"})
```

2020-03-12 14:49 UTC, evergreen-david commented on account/tests.py
> +client = Client()
전역변수 삭제 부탁 드립니다.

2020-03-12 14:49 UTC, evergreen-david commented on account/views.py
> +    @Validation_Check
패스워드 유효성 체크가 Validation_Check 안에 있어서 스페이스가 포함된 비밀번호 자체가 입력이 안되서 비교후에 에러를 리턴하는게 자연스러워 보입니다.

2020-03-12 14:49 UTC, evergreen-david commented on account/utils.py
> +            return bool(re.search(' ', string))
패스워드 validation 좀더 보강을 부탁 드립니다.

2020-03-12 14:49 UTC, evergreen-david commented on account/utils.py
> +
빈칸은 삭제해주세요

2020-03-12 14:49 UTC, evergreen-david commented on account/utils.py
> +class Login_Check:
유닛 테스트 확인 부탁 드립니다.

2020-03-13 04:42 UTC, Wave1994-Hoon commented on account/utils.py
> +
빈칸 삭제했습니다.

2020-03-13 04:42 UTC, Wave1994-Hoon commented on account/utils.py
> +
Validation_Check 클래스 삭제했습니다.

2020-03-13 04:42 UTC, Wave1994-Hoon commented on account/tests.py
> +        self.assertEqual(response.json(), {"message" : "INVALUD_KEY"})
오타 수정했습니다.

2020-03-13 04:42 UTC, Wave1994-Hoon commented on account/tests.py
> +client = Client()
전역변수 삭제 하였습니다.

2020-03-13 04:43 UTC, Wave1994-Hoon commented on account/views.py
> +    @Validation_Check
Validation_Check 클래스 삭제하였습니다.

2020-03-13 04:43 UTC, Wave1994-Hoon commented on account/utils.py
> +            return bool(re.search(' ', string))
대소문자, 길이, 공백 체크하는 함수 추가하였습니다.

2020-03-13 04:44 UTC, Wave1994-Hoon commented on account/utils.py
> +
빈칸 삭제하였습니다.

2020-03-13 06:16 UTC, evergreen-david commented on account/utils.py
> +def validate_spciel_char(email):
```suggestion
def validate_special_char(email):
```

2020-03-13 06:38 UTC, evergreen-david commented on account/views.py
> +            return JsonResponse({"message" : DOES_NOT_EXIST}, status=400)
```suggestion
            return JsonResponse(status=400)
```

2020-03-13 08:05 UTC, devops-andrew requested changes

2020-03-13 08:05 UTC, ulfrid commented on account/tests.py
> +class SignUp(TestCase):
SignIn이신거죠?

2020-03-13 08:41 UTC, evergreen-david commented on account/models.py
> +    name         = models.CharField(max_length=50, null=True)
유저 이름 null True로 하여도 가입이 되는지 확인을 부탁 드립니다.

2020-03-13 09:25 UTC, merged